/home/test/big-drive//subjects/sed/source//sed.exe --quiet ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t1 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe --silent ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t2 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -V ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t3 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe --version ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t4 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t5 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' -e '/cat$/d' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t6 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s7_0.sed' -f '../inputs/scr/s7_1.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t7 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/DOG/' -f '../inputs/scr/s8_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t8 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe --expression='s/dog/cat/' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t9 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe --file=../inputs/scr/s10_0.sed ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t10 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t11 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t12 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e '' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t13 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/nonexist.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t14 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t15 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/; =' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t16 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s17_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t17 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s18_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t18 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s19_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t19 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s20_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t20 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -n -e '=' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t21 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s22_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t22 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s23_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t23 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s24_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t24 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s25_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t25 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s26_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t26 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s27_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t27 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s28_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t28 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s29_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t29 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s30_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t30 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s31_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t31 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/nonexist.in  > /home/test/big-drive//subjects/sed/outputs/t32 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' < /home/test/big-drive//subjects/sed/inputs/stdin.in > /home/test/big-drive//subjects/sed/outputs/t33 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/default.in ../inputs/default2.in  > /home/test/big-drive//subjects/sed/outputs/t34 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/biglines.in  > /home/test/big-drive//subjects/sed/outputs/t35 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/binary.exe  > /home/test/big-drive//subjects/sed/outputs/t36 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -ne '/cat$/d;p' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t37 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -ne 's/cat/CAT/gpw s38_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t38 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -ne 's/cat/dog/gpw s39_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t39 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -ne '1,23p; s/cat/CAT/gpw s40_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t40 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s41_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t41 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s42_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t42 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s43_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t43 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s44_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t44 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s45_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t45 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s46_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t46 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s47_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t47 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s48_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t48 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s49_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t49 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s50_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t50 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s51_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t51 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s52_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t52 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s53_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t53 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s54_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t54 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s55_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t55 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s56_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t56 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s57_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t57 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s58_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t58 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s59_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t59 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s60_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t60 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s61_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t61 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s62_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t62 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s63_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t63 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s64_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t64 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s65_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t65 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s66_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t66 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s67_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t67 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s68_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t68 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s69_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t69 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s70_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t70 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s71_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t71 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s72_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t72 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s73_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t73 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s74_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t74 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s75_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t75 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s76_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t76 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s77_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t77 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s78_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t78 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s79_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t79 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s80_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t80 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s81_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t81 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s82_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t82 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s83_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t83 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s84_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t84 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s85_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t85 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s86_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t86 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s87_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t87 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s88_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t88 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s89_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t89 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s90_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t90 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s91_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t91 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s92_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t92 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s93_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t93 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s94_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t94 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s95_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t95 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s96_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t96 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s97_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t97 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s98_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t98 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s99_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t99 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s100_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t100 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s101_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t101 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s102_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t102 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s103_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t103 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s104_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t104 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s105_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t105 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s106_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t106 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s107_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t107 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s108_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t108 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s109_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t109 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s110_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t110 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s111_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t111 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s112_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t112 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s113_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t113 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s114_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t114 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s115_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t115 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s116_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t116 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s117_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t117 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s118_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t118 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s119_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t119 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s120_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t120 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s121_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t121 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s122_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t122 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s123_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t123 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s124_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t124 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s125_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t125 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s126_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t126 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s127_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t127 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s128_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t128 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s129_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t129 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s130_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t130 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s131_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t131 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s132_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t132 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s133_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t133 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s134_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t134 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s135_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t135 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s136_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t136 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s137_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t137 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s138_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t138 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s139_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t139 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s140_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t140 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s141_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t141 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s142_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t142 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s143_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t143 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s144_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t144 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s145_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t145 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s146_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t146 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s147_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t147 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s148_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t148 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s149_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t149 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s150_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t150 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s151_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t151 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s152_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t152 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s153_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t153 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s154_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t154 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s155_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t155 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s156_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t156 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s157_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t157 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s158_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t158 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s159_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t159 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s160_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t160 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s161_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t161 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s162_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t162 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s163_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t163 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s164_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t164 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s165_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t165 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s166_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t166 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s167_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t167 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s168_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t168 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s169_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t169 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s170_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t170 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s171_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t171 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s172_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t172 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s173_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t173 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s174_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t174 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s175_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t175 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s176_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t176 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s177_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t177 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s178_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t178 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s179_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t179 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s180_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t180 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s181_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t181 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s182_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t182 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s183_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t183 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s184_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t184 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s185_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t185 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s186_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t186 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s187_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t187 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s188_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t188 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s189_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t189 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s190_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t190 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s191_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t191 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s192_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t192 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s193_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t193 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s194_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t194 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s195_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t195 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s196_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t196 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s197_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t197 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s198_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t198 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s199_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t199 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s200_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t200 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s201_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t201 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s202_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t202 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s203_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t203 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s204_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t204 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s205_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t205 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s206_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t206 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s207_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t207 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s208_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t208 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s209_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t209 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s210_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t210 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s211_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t211 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s212_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t212 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s213_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t213 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s214_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t214 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s215_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t215 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s216_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t216 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s217_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t217 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s218_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t218 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s219_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t219 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s220_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t220 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s221_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t221 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s222_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t222 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s223_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t223 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s224_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t224 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s225_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t225 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s226_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t226 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s227_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t227 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s228_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t228 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s229_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t229 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s230_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t230 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s231_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t231 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s232_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t232 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s233_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t233 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s234_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t234 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s235_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t235 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s236_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t236 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s237_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t237 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s238_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t238 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s239_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t239 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s240_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t240 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s241_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t241 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s242_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t242 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s243_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t243 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s244_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t244 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s245_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t245 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s246_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t246 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s247_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t247 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s248_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t248 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e '/cat$/d' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t249 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/cat/CAT/gw s250_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t250 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/cat/dog/gw s251_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t251 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -e '1,5p; s/dog/DOG/gw s252_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t252 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s253_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t253 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s254_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t254 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s255_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t255 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s256_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t256 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s257_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t257 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s258_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t258 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s259_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t259 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s260_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t260 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s261_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t261 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s262_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t262 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s263_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t263 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s264_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t264 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s265_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t265 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s266_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t266 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s267_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t267 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s268_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t268 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s269_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t269 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s270_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t270 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s271_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t271 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s272_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t272 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s273_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t273 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s274_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t274 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s275_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t275 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s276_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t276 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s277_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t277 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s278_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t278 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s279_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t279 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s280_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t280 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s281_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t281 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s282_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t282 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s283_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t283 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s284_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t284 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s285_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t285 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s286_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t286 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s287_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t287 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s288_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t288 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s289_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t289 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s290_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t290 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s291_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t291 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s292_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t292 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s293_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t293 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s294_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t294 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s295_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t295 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s296_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t296 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s297_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t297 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s298_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t298 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s299_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t299 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s300_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t300 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s301_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t301 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s302_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t302 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s303_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t303 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s304_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t304 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s305_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t305 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s306_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t306 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s307_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t307 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s308_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t308 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s309_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t309 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s310_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t310 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s311_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t311 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s312_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t312 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s313_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t313 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s314_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t314 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s315_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t315 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s316_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t316 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s317_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t317 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s318_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t318 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s319_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t319 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s320_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t320 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s321_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t321 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s322_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t322 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s323_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t323 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s324_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t324 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s325_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t325 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s326_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t326 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s327_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t327 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s328_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t328 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s329_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t329 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s330_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t330 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s331_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t331 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s332_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t332 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s333_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t333 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s334_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t334 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s335_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t335 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s336_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t336 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s337_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t337 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s338_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t338 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s339_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t339 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s340_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t340 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s341_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t341 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s342_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t342 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s343_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t343 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s344_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t344 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s345_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t345 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s346_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t346 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s347_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t347 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s348_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t348 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s349_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t349 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s350_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t350 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s351_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t351 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s352_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t352 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s353_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t353 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s354_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t354 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s355_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t355 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s356_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t356 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s357_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t357 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s358_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t358 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s359_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t359 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s360_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t360 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s361_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t361 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s362_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t362 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s363_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t363 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -ibak -e's/s/\\/g' ../inputs/inplace.in  > /home/test/big-drive//subjects/sed/outputs/t364 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -i -e's/\\/s/g' ../inputs/inplace.in  > /home/test/big-drive//subjects/sed/outputs/t365 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -l 16 -e's/dog/cat/g; l' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t366 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -r -e's/([Cc]at)|([Dd]og)/MEOWBARK/g' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t367 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -s -e's/dog/cat/gpw s368_0.wout' ../inputs/default.in ../inputs/default2.in  > /home/test/big-drive//subjects/sed/outputs/t368 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -u -e's/dog/DOG/gp' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t369 2>&1
/home/test/big-drive//subjects/sed/source//sed.exe -rsul 20 -e's/([Cc]at)|([Dd]og)/MEOWBARK/g; l' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t370 2>&1
