#!/bin/sh
#
# STImpL Test Script generated by 
# MakeTestScript on Dec 15, 2022 at 10:17:28 PM
# by the command: 
#  java sir.mts.MakeTestScript "--no-escapes" "--stimple-file" "/home/test/big-d
#  rive//subjects/sed/testplans.alt//v3/tsl.universe" "--script-name" "/tmp/prio
#  _WlLhYE" "--experiment-dir" "/home/test/big-drive//subjects/sed" "--exe-name"
#   "/home/test/big-drive//subjects/sed/source//sed.exe" "--target" "bsh" "--pri
#  nt-config"

echo ">>>>>>>>running test 1"
#t1: "quiet" output
/home/test/big-drive//subjects/sed/source//sed.exe --quiet ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t1 2>&1

echo ">>>>>>>>running test 2"
#t2: "silent" output
/home/test/big-drive//subjects/sed/source//sed.exe --silent ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t2 2>&1

echo ">>>>>>>>running test 3"
#t3: test version (-V) output
/home/test/big-drive//subjects/sed/source//sed.exe -V ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t3 2>&1

echo ">>>>>>>>running test 4"
#t4: test version (--version) output
/home/test/big-drive//subjects/sed/source//sed.exe --version ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t4 2>&1

echo ">>>>>>>>running test 5"
#t5: no command source given
/home/test/big-drive//subjects/sed/source//sed.exe ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t5 2>&1

echo ">>>>>>>>running test 6"
#t6: multiple -e commands
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' -e '/cat$/d' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t6 2>&1

echo ">>>>>>>>running test 7"
#t7: multiple -f commands
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s7_0.sed' -f '../inputs/scr/s7_1.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t7 2>&1

echo ">>>>>>>>running test 8"
#t8: mixed -e and -f commands
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/DOG/' -f '../inputs/scr/s8_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t8 2>&1

echo ">>>>>>>>running test 9"
#t9: --expression=
/home/test/big-drive//subjects/sed/source//sed.exe --expression='s/dog/cat/' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t9 2>&1

echo ">>>>>>>>running test 10"
#t10: --file=
/home/test/big-drive//subjects/sed/source//sed.exe --file=../inputs/scr/s10_0.sed ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t10 2>&1

echo ">>>>>>>>running test 11"
#t11: no -e command given
/home/test/big-drive//subjects/sed/source//sed.exe ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t11 2>&1

echo ">>>>>>>>running test 12"
#t12: no -f command given
/home/test/big-drive//subjects/sed/source//sed.exe ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t12 2>&1

echo ">>>>>>>>running test 13"
#t13: -e with empty command
/home/test/big-drive//subjects/sed/source//sed.exe -e '' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t13 2>&1

echo ">>>>>>>>running test 14"
#t14: -f but script doesn't exist
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/nonexist.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t14 2>&1

echo ">>>>>>>>running test 15"
#t15: -f but no script file specified
/home/test/big-drive//subjects/sed/source//sed.exe -f '' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t15 2>&1

echo ">>>>>>>>running test 16"
#t16: multiple commands on single line
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/; =' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t16 2>&1

echo ">>>>>>>>running test 17"
#t17: improper spacing of commands on single line
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s17_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t17 2>&1

echo ">>>>>>>>running test 18"
#t18: no closing bracket in file
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s18_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t18 2>&1

echo ">>>>>>>>running test 19"
#t19: too many open filehandles
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s19_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t19 2>&1

echo ">>>>>>>>running test 20"
#t20: next/Next in same address
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s20_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t20 2>&1

echo ">>>>>>>>running test 21"
#t21: print line numbers
/home/test/big-drive//subjects/sed/source//sed.exe -n -e '=' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t21 2>&1

echo ">>>>>>>>running test 22"
#t22: script with hold/get
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s22_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t22 2>&1

echo ">>>>>>>>running test 23"
#t23: script with hold/Get
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s23_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t23 2>&1

echo ">>>>>>>>running test 24"
#t24: script with Hold/get
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s24_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t24 2>&1

echo ">>>>>>>>running test 25"
#t25: script with Hold/Get
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s25_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t25 2>&1

echo ">>>>>>>>running test 26"
#t26: script with hold/get and swap
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s26_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t26 2>&1

echo ">>>>>>>>running test 27"
#t27: single branch (b)
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s27_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t27 2>&1

echo ">>>>>>>>running test 28"
#t28: multi branch (b)
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s28_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t28 2>&1

echo ">>>>>>>>running test 29"
#t29: single test (t)
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s29_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t29 2>&1

echo ">>>>>>>>running test 30"
#t30: multi test (t)
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s30_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t30 2>&1

echo ">>>>>>>>running test 31"
#t31: nested branch/test
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s31_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t31 2>&1

echo ">>>>>>>>running test 32"
#t32: input file does not exist
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/nonexist.in  > /home/test/big-drive//subjects/sed/outputs/t32 2>&1

echo ">>>>>>>>running test 33"
#t33: no input file given
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' < /home/test/big-drive//subjects/sed/inputs/stdin.in > /home/test/big-drive//subjects/sed/outputs/t33 2>&1

echo ">>>>>>>>running test 34"
#t34: multiple input files
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/default.in ../inputs/default2.in  > /home/test/big-drive//subjects/sed/outputs/t34 2>&1

echo ">>>>>>>>running test 35"
#t35: line length > 4000 bytes
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/biglines.in  > /home/test/big-drive//subjects/sed/outputs/t35 2>&1

echo ">>>>>>>>running test 36"
#t36: binary file type
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/dog/cat/' ../inputs/binary.exe  > /home/test/big-drive//subjects/sed/outputs/t36 2>&1

echo ">>>>>>>>running test 37"
#t37: delete + print
/home/test/big-drive//subjects/sed/source//sed.exe -ne '/cat$/d;p' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t37 2>&1

echo ">>>>>>>>running test 38"
#t38: sub + gpw
/home/test/big-drive//subjects/sed/source//sed.exe -ne 's/cat/CAT/gpw s38_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t38 2>&1
mv s38_0.wout /home/test/big-drive//subjects/sed/outputs/s38.wout

echo ">>>>>>>>running test 39"
#t39: sub + gpw + d
/home/test/big-drive//subjects/sed/source//sed.exe -ne 's/cat/dog/gpw s39_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t39 2>&1
mv s39_0.wout /home/test/big-drive//subjects/sed/outputs/s39.wout

echo ">>>>>>>>running test 40"
#t40: sub + gpw + D
/home/test/big-drive//subjects/sed/source//sed.exe -ne '1,23p; s/cat/CAT/gpw s40_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t40 2>&1
mv s40_0.wout /home/test/big-drive//subjects/sed/outputs/s40.wout

echo ">>>>>>>>running test 41"
#t41: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s41_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t41 2>&1

echo ">>>>>>>>running test 42"
#t42: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s42_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t42 2>&1

echo ">>>>>>>>running test 43"
#t43: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s43_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t43 2>&1

echo ">>>>>>>>running test 44"
#t44: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s44_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t44 2>&1

echo ">>>>>>>>running test 45"
#t45: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s45_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t45 2>&1

echo ">>>>>>>>running test 46"
#t46: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s46_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t46 2>&1

echo ">>>>>>>>running test 47"
#t47: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s47_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t47 2>&1

echo ">>>>>>>>running test 48"
#t48: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s48_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t48 2>&1

echo ">>>>>>>>running test 49"
#t49: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s49_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t49 2>&1

echo ">>>>>>>>running test 50"
#t50: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s50_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t50 2>&1

echo ">>>>>>>>running test 51"
#t51: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s51_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t51 2>&1

echo ">>>>>>>>running test 52"
#t52: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s52_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t52 2>&1

echo ">>>>>>>>running test 53"
#t53: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s53_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t53 2>&1

echo ">>>>>>>>running test 54"
#t54: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s54_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t54 2>&1

echo ">>>>>>>>running test 55"
#t55: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s55_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t55 2>&1

echo ">>>>>>>>running test 56"
#t56: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s56_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t56 2>&1

echo ">>>>>>>>running test 57"
#t57: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s57_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t57 2>&1

echo ">>>>>>>>running test 58"
#t58: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s58_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t58 2>&1

echo ">>>>>>>>running test 59"
#t59: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s59_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t59 2>&1

echo ">>>>>>>>running test 60"
#t60: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s60_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t60 2>&1

echo ">>>>>>>>running test 61"
#t61: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s61_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t61 2>&1

echo ">>>>>>>>running test 62"
#t62: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s62_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t62 2>&1

echo ">>>>>>>>running test 63"
#t63: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s63_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t63 2>&1

echo ">>>>>>>>running test 64"
#t64: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s64_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t64 2>&1

echo ">>>>>>>>running test 65"
#t65: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s65_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t65 2>&1
mv s65_0.wout /home/test/big-drive//subjects/sed/outputs/s65.wout

echo ">>>>>>>>running test 66"
#t66: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s66_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t66 2>&1
mv s66_0.wout /home/test/big-drive//subjects/sed/outputs/s66.wout

echo ">>>>>>>>running test 67"
#t67: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s67_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t67 2>&1
mv s67_0.wout /home/test/big-drive//subjects/sed/outputs/s67.wout

echo ">>>>>>>>running test 68"
#t68: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s68_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t68 2>&1
mv s68_0.wout /home/test/big-drive//subjects/sed/outputs/s68.wout

echo ">>>>>>>>running test 69"
#t69: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s69_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t69 2>&1

echo ">>>>>>>>running test 70"
#t70: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s70_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t70 2>&1

echo ">>>>>>>>running test 71"
#t71: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s71_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t71 2>&1

echo ">>>>>>>>running test 72"
#t72: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s72_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t72 2>&1

echo ">>>>>>>>running test 73"
#t73: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s73_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t73 2>&1

echo ">>>>>>>>running test 74"
#t74: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s74_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t74 2>&1

echo ">>>>>>>>running test 75"
#t75: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s75_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t75 2>&1

echo ">>>>>>>>running test 76"
#t76: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s76_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t76 2>&1

echo ">>>>>>>>running test 77"
#t77: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s77_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t77 2>&1

echo ">>>>>>>>running test 78"
#t78: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s78_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t78 2>&1

echo ">>>>>>>>running test 79"
#t79: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s79_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t79 2>&1

echo ">>>>>>>>running test 80"
#t80: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s80_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t80 2>&1

echo ">>>>>>>>running test 81"
#t81: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s81_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t81 2>&1

echo ">>>>>>>>running test 82"
#t82: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s82_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t82 2>&1

echo ">>>>>>>>running test 83"
#t83: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s83_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t83 2>&1

echo ">>>>>>>>running test 84"
#t84: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s84_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t84 2>&1

echo ">>>>>>>>running test 85"
#t85: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s85_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t85 2>&1

echo ">>>>>>>>running test 86"
#t86: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s86_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t86 2>&1

echo ">>>>>>>>running test 87"
#t87: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s87_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t87 2>&1

echo ">>>>>>>>running test 88"
#t88: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s88_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t88 2>&1

echo ">>>>>>>>running test 89"
#t89: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s89_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t89 2>&1

echo ">>>>>>>>running test 90"
#t90: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s90_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t90 2>&1

echo ">>>>>>>>running test 91"
#t91: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s91_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t91 2>&1

echo ">>>>>>>>running test 92"
#t92: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s92_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t92 2>&1

echo ">>>>>>>>running test 93"
#t93: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s93_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t93 2>&1

echo ">>>>>>>>running test 94"
#t94: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s94_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t94 2>&1

echo ">>>>>>>>running test 95"
#t95: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s95_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t95 2>&1

echo ">>>>>>>>running test 96"
#t96: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s96_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t96 2>&1

echo ">>>>>>>>running test 97"
#t97: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s97_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t97 2>&1

echo ">>>>>>>>running test 98"
#t98: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s98_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t98 2>&1

echo ">>>>>>>>running test 99"
#t99: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s99_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t99 2>&1

echo ">>>>>>>>running test 100"
#t100: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s100_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t100 2>&1

echo ">>>>>>>>running test 101"
#t101: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s101_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t101 2>&1
mv s101_0.wout /home/test/big-drive//subjects/sed/outputs/s101.wout

echo ">>>>>>>>running test 102"
#t102: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s102_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t102 2>&1
mv s102_0.wout /home/test/big-drive//subjects/sed/outputs/s102.wout

echo ">>>>>>>>running test 103"
#t103: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s103_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t103 2>&1
mv s103_0.wout /home/test/big-drive//subjects/sed/outputs/s103.wout

echo ">>>>>>>>running test 104"
#t104: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s104_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t104 2>&1
mv s104_0.wout /home/test/big-drive//subjects/sed/outputs/s104.wout

echo ">>>>>>>>running test 105"
#t105: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s105_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t105 2>&1

echo ">>>>>>>>running test 106"
#t106: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s106_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t106 2>&1

echo ">>>>>>>>running test 107"
#t107: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s107_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t107 2>&1

echo ">>>>>>>>running test 108"
#t108: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s108_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t108 2>&1

echo ">>>>>>>>running test 109"
#t109: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s109_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t109 2>&1

echo ">>>>>>>>running test 110"
#t110: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s110_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t110 2>&1

echo ">>>>>>>>running test 111"
#t111: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s111_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t111 2>&1

echo ">>>>>>>>running test 112"
#t112: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s112_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t112 2>&1

echo ">>>>>>>>running test 113"
#t113: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s113_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t113 2>&1
mv s113_0.wout /home/test/big-drive//subjects/sed/outputs/s113.wout

echo ">>>>>>>>running test 114"
#t114: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s114_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t114 2>&1
mv s114_0.wout /home/test/big-drive//subjects/sed/outputs/s114.wout

echo ">>>>>>>>running test 115"
#t115: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s115_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t115 2>&1
mv s115_0.wout /home/test/big-drive//subjects/sed/outputs/s115.wout

echo ">>>>>>>>running test 116"
#t116: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s116_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t116 2>&1
mv s116_0.wout /home/test/big-drive//subjects/sed/outputs/s116.wout

echo ">>>>>>>>running test 117"
#t117: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s117_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t117 2>&1
mv s117_0.wout /home/test/big-drive//subjects/sed/outputs/s117.wout

echo ">>>>>>>>running test 118"
#t118: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s118_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t118 2>&1
mv s118_0.wout /home/test/big-drive//subjects/sed/outputs/s118.wout

echo ">>>>>>>>running test 119"
#t119: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s119_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t119 2>&1
mv s119_0.wout /home/test/big-drive//subjects/sed/outputs/s119.wout

echo ">>>>>>>>running test 120"
#t120: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s120_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t120 2>&1
mv s120_0.wout /home/test/big-drive//subjects/sed/outputs/s120.wout

echo ">>>>>>>>running test 121"
#t121: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s121_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t121 2>&1
mv s121_0.wout /home/test/big-drive//subjects/sed/outputs/s121.wout

echo ">>>>>>>>running test 122"
#t122: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s122_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t122 2>&1
mv s122_0.wout /home/test/big-drive//subjects/sed/outputs/s122.wout

echo ">>>>>>>>running test 123"
#t123: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s123_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t123 2>&1
mv s123_0.wout /home/test/big-drive//subjects/sed/outputs/s123.wout

echo ">>>>>>>>running test 124"
#t124: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s124_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t124 2>&1
mv s124_0.wout /home/test/big-drive//subjects/sed/outputs/s124.wout

echo ">>>>>>>>running test 125"
#t125: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s125_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t125 2>&1
mv s125_0.wout /home/test/big-drive//subjects/sed/outputs/s125.wout

echo ">>>>>>>>running test 126"
#t126: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s126_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t126 2>&1
mv s126_0.wout /home/test/big-drive//subjects/sed/outputs/s126.wout

echo ">>>>>>>>running test 127"
#t127: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s127_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t127 2>&1
mv s127_0.wout /home/test/big-drive//subjects/sed/outputs/s127.wout

echo ">>>>>>>>running test 128"
#t128: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s128_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t128 2>&1
mv s128_0.wout /home/test/big-drive//subjects/sed/outputs/s128.wout

echo ">>>>>>>>running test 129"
#t129: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s129_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t129 2>&1
mv s129_0.wout /home/test/big-drive//subjects/sed/outputs/s129.wout

echo ">>>>>>>>running test 130"
#t130: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s130_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t130 2>&1
mv s130_0.wout /home/test/big-drive//subjects/sed/outputs/s130.wout

echo ">>>>>>>>running test 131"
#t131: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s131_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t131 2>&1
mv s131_0.wout /home/test/big-drive//subjects/sed/outputs/s131.wout

echo ">>>>>>>>running test 132"
#t132: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s132_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t132 2>&1
mv s132_0.wout /home/test/big-drive//subjects/sed/outputs/s132.wout

echo ">>>>>>>>running test 133"
#t133: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s133_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t133 2>&1
mv s133_0.wout /home/test/big-drive//subjects/sed/outputs/s133.wout

echo ">>>>>>>>running test 134"
#t134: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s134_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t134 2>&1
mv s134_0.wout /home/test/big-drive//subjects/sed/outputs/s134.wout

echo ">>>>>>>>running test 135"
#t135: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s135_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t135 2>&1
mv s135_0.wout /home/test/big-drive//subjects/sed/outputs/s135.wout

echo ">>>>>>>>running test 136"
#t136: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s136_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t136 2>&1
mv s136_0.wout /home/test/big-drive//subjects/sed/outputs/s136.wout

echo ">>>>>>>>running test 137"
#t137: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s137_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t137 2>&1
mv s137_0.wout /home/test/big-drive//subjects/sed/outputs/s137.wout

echo ">>>>>>>>running test 138"
#t138: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s138_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t138 2>&1
mv s138_0.wout /home/test/big-drive//subjects/sed/outputs/s138.wout

echo ">>>>>>>>running test 139"
#t139: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s139_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t139 2>&1
mv s139_0.wout /home/test/big-drive//subjects/sed/outputs/s139.wout

echo ">>>>>>>>running test 140"
#t140: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s140_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t140 2>&1
mv s140_0.wout /home/test/big-drive//subjects/sed/outputs/s140.wout

echo ">>>>>>>>running test 141"
#t141: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s141_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t141 2>&1
mv s141_0.wout /home/test/big-drive//subjects/sed/outputs/s141.wout

echo ">>>>>>>>running test 142"
#t142: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s142_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t142 2>&1
mv s142_0.wout /home/test/big-drive//subjects/sed/outputs/s142.wout

echo ">>>>>>>>running test 143"
#t143: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s143_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t143 2>&1
mv s143_0.wout /home/test/big-drive//subjects/sed/outputs/s143.wout

echo ">>>>>>>>running test 144"
#t144: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s144_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t144 2>&1
mv s144_0.wout /home/test/big-drive//subjects/sed/outputs/s144.wout

echo ">>>>>>>>running test 145"
#t145: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s145_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t145 2>&1
mv s145_0.wout /home/test/big-drive//subjects/sed/outputs/s145.wout

echo ">>>>>>>>running test 146"
#t146: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s146_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t146 2>&1
mv s146_0.wout /home/test/big-drive//subjects/sed/outputs/s146.wout

echo ">>>>>>>>running test 147"
#t147: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s147_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t147 2>&1
mv s147_0.wout /home/test/big-drive//subjects/sed/outputs/s147.wout

echo ">>>>>>>>running test 148"
#t148: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s148_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t148 2>&1
mv s148_0.wout /home/test/big-drive//subjects/sed/outputs/s148.wout

echo ">>>>>>>>running test 149"
#t149: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s149_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t149 2>&1
mv s149_0.wout /home/test/big-drive//subjects/sed/outputs/s149.wout

echo ">>>>>>>>running test 150"
#t150: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s150_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t150 2>&1
mv s150_0.wout /home/test/big-drive//subjects/sed/outputs/s150.wout

echo ">>>>>>>>running test 151"
#t151: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s151_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t151 2>&1
mv s151_0.wout /home/test/big-drive//subjects/sed/outputs/s151.wout

echo ">>>>>>>>running test 152"
#t152: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s152_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t152 2>&1
mv s152_0.wout /home/test/big-drive//subjects/sed/outputs/s152.wout

echo ">>>>>>>>running test 153"
#t153: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s153_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t153 2>&1
mv s153_0.wout /home/test/big-drive//subjects/sed/outputs/s153.wout

echo ">>>>>>>>running test 154"
#t154: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s154_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t154 2>&1
mv s154_0.wout /home/test/big-drive//subjects/sed/outputs/s154.wout

echo ">>>>>>>>running test 155"
#t155: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s155_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t155 2>&1
mv s155_0.wout /home/test/big-drive//subjects/sed/outputs/s155.wout

echo ">>>>>>>>running test 156"
#t156: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s156_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t156 2>&1
mv s156_0.wout /home/test/big-drive//subjects/sed/outputs/s156.wout

echo ">>>>>>>>running test 157"
#t157: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s157_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t157 2>&1
mv s157_0.wout /home/test/big-drive//subjects/sed/outputs/s157.wout

echo ">>>>>>>>running test 158"
#t158: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s158_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t158 2>&1
mv s158_0.wout /home/test/big-drive//subjects/sed/outputs/s158.wout

echo ">>>>>>>>running test 159"
#t159: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s159_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t159 2>&1
mv s159_0.wout /home/test/big-drive//subjects/sed/outputs/s159.wout

echo ">>>>>>>>running test 160"
#t160: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s160_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t160 2>&1
mv s160_0.wout /home/test/big-drive//subjects/sed/outputs/s160.wout

echo ">>>>>>>>running test 161"
#t161: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s161_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t161 2>&1
mv s161_0.wout /home/test/big-drive//subjects/sed/outputs/s161.wout

echo ">>>>>>>>running test 162"
#t162: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s162_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t162 2>&1
mv s162_0.wout /home/test/big-drive//subjects/sed/outputs/s162.wout

echo ">>>>>>>>running test 163"
#t163: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s163_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t163 2>&1
mv s163_0.wout /home/test/big-drive//subjects/sed/outputs/s163.wout

echo ">>>>>>>>running test 164"
#t164: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s164_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t164 2>&1
mv s164_0.wout /home/test/big-drive//subjects/sed/outputs/s164.wout

echo ">>>>>>>>running test 165"
#t165: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s165_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t165 2>&1
mv s165_0.wout /home/test/big-drive//subjects/sed/outputs/s165.wout

echo ">>>>>>>>running test 166"
#t166: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s166_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t166 2>&1
mv s166_0.wout /home/test/big-drive//subjects/sed/outputs/s166.wout

echo ">>>>>>>>running test 167"
#t167: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s167_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t167 2>&1
mv s167_0.wout /home/test/big-drive//subjects/sed/outputs/s167.wout

echo ">>>>>>>>running test 168"
#t168: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s168_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t168 2>&1
mv s168_0.wout /home/test/big-drive//subjects/sed/outputs/s168.wout

echo ">>>>>>>>running test 169"
#t169: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s169_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t169 2>&1
mv s169_0.wout /home/test/big-drive//subjects/sed/outputs/s169.wout

echo ">>>>>>>>running test 170"
#t170: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s170_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t170 2>&1
mv s170_0.wout /home/test/big-drive//subjects/sed/outputs/s170.wout

echo ">>>>>>>>running test 171"
#t171: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s171_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t171 2>&1
mv s171_0.wout /home/test/big-drive//subjects/sed/outputs/s171.wout

echo ">>>>>>>>running test 172"
#t172: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s172_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t172 2>&1
mv s172_0.wout /home/test/big-drive//subjects/sed/outputs/s172.wout

echo ">>>>>>>>running test 173"
#t173: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s173_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t173 2>&1
mv s173_0.wout /home/test/big-drive//subjects/sed/outputs/s173.wout

echo ">>>>>>>>running test 174"
#t174: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s174_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t174 2>&1
mv s174_0.wout /home/test/big-drive//subjects/sed/outputs/s174.wout

echo ">>>>>>>>running test 175"
#t175: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s175_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t175 2>&1
mv s175_0.wout /home/test/big-drive//subjects/sed/outputs/s175.wout

echo ">>>>>>>>running test 176"
#t176: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s176_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t176 2>&1
mv s176_0.wout /home/test/big-drive//subjects/sed/outputs/s176.wout

echo ">>>>>>>>running test 177"
#t177: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s177_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t177 2>&1
mv s177_0.wout /home/test/big-drive//subjects/sed/outputs/s177.wout

echo ">>>>>>>>running test 178"
#t178: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s178_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t178 2>&1
mv s178_0.wout /home/test/big-drive//subjects/sed/outputs/s178.wout

echo ">>>>>>>>running test 179"
#t179: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s179_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t179 2>&1
mv s179_0.wout /home/test/big-drive//subjects/sed/outputs/s179.wout

echo ">>>>>>>>running test 180"
#t180: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s180_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t180 2>&1
mv s180_0.wout /home/test/big-drive//subjects/sed/outputs/s180.wout

echo ">>>>>>>>running test 181"
#t181: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s181_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t181 2>&1
mv s181_0.wout /home/test/big-drive//subjects/sed/outputs/s181.wout

echo ">>>>>>>>running test 182"
#t182: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s182_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t182 2>&1
mv s182_0.wout /home/test/big-drive//subjects/sed/outputs/s182.wout

echo ">>>>>>>>running test 183"
#t183: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s183_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t183 2>&1
mv s183_0.wout /home/test/big-drive//subjects/sed/outputs/s183.wout

echo ">>>>>>>>running test 184"
#t184: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s184_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t184 2>&1
mv s184_0.wout /home/test/big-drive//subjects/sed/outputs/s184.wout

echo ">>>>>>>>running test 185"
#t185: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s185_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t185 2>&1
mv s185_0.wout /home/test/big-drive//subjects/sed/outputs/s185.wout

echo ">>>>>>>>running test 186"
#t186: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s186_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t186 2>&1
mv s186_0.wout /home/test/big-drive//subjects/sed/outputs/s186.wout

echo ">>>>>>>>running test 187"
#t187: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s187_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t187 2>&1
mv s187_0.wout /home/test/big-drive//subjects/sed/outputs/s187.wout

echo ">>>>>>>>running test 188"
#t188: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s188_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t188 2>&1
mv s188_0.wout /home/test/big-drive//subjects/sed/outputs/s188.wout

echo ">>>>>>>>running test 189"
#t189: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s189_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t189 2>&1
mv s189_0.wout /home/test/big-drive//subjects/sed/outputs/s189.wout

echo ">>>>>>>>running test 190"
#t190: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s190_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t190 2>&1
mv s190_0.wout /home/test/big-drive//subjects/sed/outputs/s190.wout

echo ">>>>>>>>running test 191"
#t191: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s191_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t191 2>&1
mv s191_0.wout /home/test/big-drive//subjects/sed/outputs/s191.wout

echo ">>>>>>>>running test 192"
#t192: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s192_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t192 2>&1
mv s192_0.wout /home/test/big-drive//subjects/sed/outputs/s192.wout

echo ">>>>>>>>running test 193"
#t193: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s193_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t193 2>&1
mv s193_0.wout /home/test/big-drive//subjects/sed/outputs/s193.wout

echo ">>>>>>>>running test 194"
#t194: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s194_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t194 2>&1
mv s194_0.wout /home/test/big-drive//subjects/sed/outputs/s194.wout

echo ">>>>>>>>running test 195"
#t195: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s195_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t195 2>&1
mv s195_0.wout /home/test/big-drive//subjects/sed/outputs/s195.wout

echo ">>>>>>>>running test 196"
#t196: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s196_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t196 2>&1
mv s196_0.wout /home/test/big-drive//subjects/sed/outputs/s196.wout

echo ">>>>>>>>running test 197"
#t197: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s197_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t197 2>&1
mv s197_0.wout /home/test/big-drive//subjects/sed/outputs/s197.wout

echo ">>>>>>>>running test 198"
#t198: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s198_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t198 2>&1
mv s198_0.wout /home/test/big-drive//subjects/sed/outputs/s198.wout

echo ">>>>>>>>running test 199"
#t199: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s199_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t199 2>&1
mv s199_0.wout /home/test/big-drive//subjects/sed/outputs/s199.wout

echo ">>>>>>>>running test 200"
#t200: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s200_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t200 2>&1
mv s200_0.wout /home/test/big-drive//subjects/sed/outputs/s200.wout

echo ">>>>>>>>running test 201"
#t201: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s201_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t201 2>&1
mv s201_0.wout /home/test/big-drive//subjects/sed/outputs/s201.wout

echo ">>>>>>>>running test 202"
#t202: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s202_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t202 2>&1
mv s202_0.wout /home/test/big-drive//subjects/sed/outputs/s202.wout

echo ">>>>>>>>running test 203"
#t203: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s203_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t203 2>&1
mv s203_0.wout /home/test/big-drive//subjects/sed/outputs/s203.wout

echo ">>>>>>>>running test 204"
#t204: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s204_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t204 2>&1
mv s204_0.wout /home/test/big-drive//subjects/sed/outputs/s204.wout

echo ">>>>>>>>running test 205"
#t205: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s205_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t205 2>&1
mv s205_0.wout /home/test/big-drive//subjects/sed/outputs/s205.wout

echo ">>>>>>>>running test 206"
#t206: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s206_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t206 2>&1
mv s206_0.wout /home/test/big-drive//subjects/sed/outputs/s206.wout

echo ">>>>>>>>running test 207"
#t207: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s207_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t207 2>&1
mv s207_0.wout /home/test/big-drive//subjects/sed/outputs/s207.wout

echo ">>>>>>>>running test 208"
#t208: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s208_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t208 2>&1
mv s208_0.wout /home/test/big-drive//subjects/sed/outputs/s208.wout

echo ">>>>>>>>running test 209"
#t209: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s209_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t209 2>&1
mv s209_0.wout /home/test/big-drive//subjects/sed/outputs/s209.wout

echo ">>>>>>>>running test 210"
#t210: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s210_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t210 2>&1
mv s210_0.wout /home/test/big-drive//subjects/sed/outputs/s210.wout

echo ">>>>>>>>running test 211"
#t211: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s211_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t211 2>&1
mv s211_0.wout /home/test/big-drive//subjects/sed/outputs/s211.wout

echo ">>>>>>>>running test 212"
#t212: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s212_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t212 2>&1
mv s212_0.wout /home/test/big-drive//subjects/sed/outputs/s212.wout

echo ">>>>>>>>running test 213"
#t213: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s213_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t213 2>&1
mv s213_0.wout /home/test/big-drive//subjects/sed/outputs/s213.wout

echo ">>>>>>>>running test 214"
#t214: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s214_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t214 2>&1
mv s214_0.wout /home/test/big-drive//subjects/sed/outputs/s214.wout

echo ">>>>>>>>running test 215"
#t215: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s215_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t215 2>&1
mv s215_0.wout /home/test/big-drive//subjects/sed/outputs/s215.wout

echo ">>>>>>>>running test 216"
#t216: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s216_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t216 2>&1
mv s216_0.wout /home/test/big-drive//subjects/sed/outputs/s216.wout

echo ">>>>>>>>running test 217"
#t217: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s217_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t217 2>&1
mv s217_0.wout /home/test/big-drive//subjects/sed/outputs/s217.wout

echo ">>>>>>>>running test 218"
#t218: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s218_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t218 2>&1
mv s218_0.wout /home/test/big-drive//subjects/sed/outputs/s218.wout

echo ">>>>>>>>running test 219"
#t219: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s219_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t219 2>&1
mv s219_0.wout /home/test/big-drive//subjects/sed/outputs/s219.wout

echo ">>>>>>>>running test 220"
#t220: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s220_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t220 2>&1
mv s220_0.wout /home/test/big-drive//subjects/sed/outputs/s220.wout

echo ">>>>>>>>running test 221"
#t221: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s221_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t221 2>&1

echo ">>>>>>>>running test 222"
#t222: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s222_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t222 2>&1

echo ">>>>>>>>running test 223"
#t223: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s223_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t223 2>&1

echo ">>>>>>>>running test 224"
#t224: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s224_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t224 2>&1

echo ">>>>>>>>running test 225"
#t225: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s225_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t225 2>&1

echo ">>>>>>>>running test 226"
#t226: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s226_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t226 2>&1

echo ">>>>>>>>running test 227"
#t227: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s227_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t227 2>&1

echo ">>>>>>>>running test 228"
#t228: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s228_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t228 2>&1

echo ">>>>>>>>running test 229"
#t229: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s229_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t229 2>&1

echo ">>>>>>>>running test 230"
#t230: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s230_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t230 2>&1

echo ">>>>>>>>running test 231"
#t231: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s231_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t231 2>&1

echo ">>>>>>>>running test 232"
#t232: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s232_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t232 2>&1

echo ">>>>>>>>running test 233"
#t233: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s233_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t233 2>&1

echo ">>>>>>>>running test 234"
#t234: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s234_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t234 2>&1

echo ">>>>>>>>running test 235"
#t235: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s235_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t235 2>&1

echo ">>>>>>>>running test 236"
#t236: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s236_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t236 2>&1

echo ">>>>>>>>running test 237"
#t237: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s237_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t237 2>&1

echo ">>>>>>>>running test 238"
#t238: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s238_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t238 2>&1

echo ">>>>>>>>running test 239"
#t239: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s239_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t239 2>&1

echo ">>>>>>>>running test 240"
#t240: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s240_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t240 2>&1

echo ">>>>>>>>running test 241"
#t241: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s241_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t241 2>&1

echo ">>>>>>>>running test 242"
#t242: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s242_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t242 2>&1

echo ">>>>>>>>running test 243"
#t243: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s243_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t243 2>&1
mv s243_0.wout /home/test/big-drive//subjects/sed/outputs/s243.wout

echo ">>>>>>>>running test 244"
#t244: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s244_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t244 2>&1
mv s244_0.wout /home/test/big-drive//subjects/sed/outputs/s244.wout

echo ">>>>>>>>running test 245"
#t245: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s245_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t245 2>&1

echo ">>>>>>>>running test 246"
#t246: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s246_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t246 2>&1

echo ">>>>>>>>running test 247"
#t247: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s247_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t247 2>&1

echo ">>>>>>>>running test 248"
#t248: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s248_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t248 2>&1

echo ">>>>>>>>running test 249"
#t249: delete + print
/home/test/big-drive//subjects/sed/source//sed.exe -e '/cat$/d' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t249 2>&1

echo ">>>>>>>>running test 250"
#t250: sub + gpw
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/cat/CAT/gw s250_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t250 2>&1
mv s250_0.wout /home/test/big-drive//subjects/sed/outputs/s250.wout

echo ">>>>>>>>running test 251"
#t251: sub + gpw + d
/home/test/big-drive//subjects/sed/source//sed.exe -e 's/cat/dog/gw s251_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t251 2>&1
mv s251_0.wout /home/test/big-drive//subjects/sed/outputs/s251.wout

echo ">>>>>>>>running test 252"
#t252: sub + gpw + D
/home/test/big-drive//subjects/sed/source//sed.exe -e '1,5p; s/dog/DOG/gw s252_0.wout' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t252 2>&1
mv s252_0.wout /home/test/big-drive//subjects/sed/outputs/s252.wout

echo ">>>>>>>>running test 253"
#t253: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s253_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t253 2>&1

echo ">>>>>>>>running test 254"
#t254: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s254_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t254 2>&1

echo ">>>>>>>>running test 255"
#t255: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s255_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t255 2>&1

echo ">>>>>>>>running test 256"
#t256: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s256_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t256 2>&1

echo ">>>>>>>>running test 257"
#t257: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s257_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t257 2>&1

echo ">>>>>>>>running test 258"
#t258: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s258_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t258 2>&1

echo ">>>>>>>>running test 259"
#t259: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s259_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t259 2>&1

echo ">>>>>>>>running test 260"
#t260: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s260_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t260 2>&1

echo ">>>>>>>>running test 261"
#t261: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s261_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t261 2>&1

echo ">>>>>>>>running test 262"
#t262: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s262_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t262 2>&1

echo ">>>>>>>>running test 263"
#t263: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s263_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t263 2>&1

echo ">>>>>>>>running test 264"
#t264: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s264_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t264 2>&1

echo ">>>>>>>>running test 265"
#t265: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s265_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t265 2>&1
mv s265_0.wout /home/test/big-drive//subjects/sed/outputs/s265.wout

echo ">>>>>>>>running test 266"
#t266: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s266_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t266 2>&1
mv s266_0.wout /home/test/big-drive//subjects/sed/outputs/s266.wout

echo ">>>>>>>>running test 267"
#t267: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s267_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t267 2>&1

echo ">>>>>>>>running test 268"
#t268: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s268_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t268 2>&1

echo ">>>>>>>>running test 269"
#t269: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s269_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t269 2>&1

echo ">>>>>>>>running test 270"
#t270: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s270_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t270 2>&1

echo ">>>>>>>>running test 271"
#t271: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s271_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t271 2>&1

echo ">>>>>>>>running test 272"
#t272: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s272_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t272 2>&1

echo ">>>>>>>>running test 273"
#t273: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s273_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t273 2>&1

echo ">>>>>>>>running test 274"
#t274: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s274_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t274 2>&1

echo ">>>>>>>>running test 275"
#t275: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s275_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t275 2>&1

echo ">>>>>>>>running test 276"
#t276: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s276_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t276 2>&1

echo ">>>>>>>>running test 277"
#t277: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s277_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t277 2>&1

echo ">>>>>>>>running test 278"
#t278: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s278_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t278 2>&1

echo ">>>>>>>>running test 279"
#t279: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s279_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t279 2>&1

echo ">>>>>>>>running test 280"
#t280: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s280_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t280 2>&1

echo ">>>>>>>>running test 281"
#t281: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s281_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t281 2>&1

echo ">>>>>>>>running test 282"
#t282: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s282_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t282 2>&1

echo ">>>>>>>>running test 283"
#t283: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s283_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t283 2>&1
mv s283_0.wout /home/test/big-drive//subjects/sed/outputs/s283.wout

echo ">>>>>>>>running test 284"
#t284: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s284_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t284 2>&1
mv s284_0.wout /home/test/big-drive//subjects/sed/outputs/s284.wout

echo ">>>>>>>>running test 285"
#t285: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s285_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t285 2>&1

echo ">>>>>>>>running test 286"
#t286: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s286_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t286 2>&1

echo ">>>>>>>>running test 287"
#t287: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s287_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t287 2>&1

echo ">>>>>>>>running test 288"
#t288: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s288_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t288 2>&1

echo ">>>>>>>>running test 289"
#t289: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s289_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t289 2>&1
mv s289_0.wout /home/test/big-drive//subjects/sed/outputs/s289.wout

echo ">>>>>>>>running test 290"
#t290: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s290_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t290 2>&1
mv s290_0.wout /home/test/big-drive//subjects/sed/outputs/s290.wout

echo ">>>>>>>>running test 291"
#t291: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s291_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t291 2>&1
mv s291_0.wout /home/test/big-drive//subjects/sed/outputs/s291.wout

echo ">>>>>>>>running test 292"
#t292: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s292_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t292 2>&1
mv s292_0.wout /home/test/big-drive//subjects/sed/outputs/s292.wout

echo ">>>>>>>>running test 293"
#t293: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s293_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t293 2>&1
mv s293_0.wout /home/test/big-drive//subjects/sed/outputs/s293.wout

echo ">>>>>>>>running test 294"
#t294: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s294_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t294 2>&1
mv s294_0.wout /home/test/big-drive//subjects/sed/outputs/s294.wout

echo ">>>>>>>>running test 295"
#t295: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s295_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t295 2>&1
mv s295_0.wout /home/test/big-drive//subjects/sed/outputs/s295.wout

echo ">>>>>>>>running test 296"
#t296: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s296_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t296 2>&1
mv s296_0.wout /home/test/big-drive//subjects/sed/outputs/s296.wout

echo ">>>>>>>>running test 297"
#t297: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s297_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t297 2>&1
mv s297_0.wout /home/test/big-drive//subjects/sed/outputs/s297.wout

echo ">>>>>>>>running test 298"
#t298: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s298_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t298 2>&1
mv s298_0.wout /home/test/big-drive//subjects/sed/outputs/s298.wout

echo ">>>>>>>>running test 299"
#t299: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s299_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t299 2>&1
mv s299_0.wout /home/test/big-drive//subjects/sed/outputs/s299.wout

echo ">>>>>>>>running test 300"
#t300: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s300_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t300 2>&1

echo ">>>>>>>>running test 301"
#t301: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s301_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t301 2>&1
mv s301_0.wout /home/test/big-drive//subjects/sed/outputs/s301.wout

echo ">>>>>>>>running test 302"
#t302: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s302_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t302 2>&1
mv s302_0.wout /home/test/big-drive//subjects/sed/outputs/s302.wout

echo ">>>>>>>>running test 303"
#t303: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s303_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t303 2>&1
mv s303_0.wout /home/test/big-drive//subjects/sed/outputs/s303.wout

echo ">>>>>>>>running test 304"
#t304: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s304_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t304 2>&1
mv s304_0.wout /home/test/big-drive//subjects/sed/outputs/s304.wout

echo ">>>>>>>>running test 305"
#t305: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s305_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t305 2>&1
mv s305_0.wout /home/test/big-drive//subjects/sed/outputs/s305.wout

echo ">>>>>>>>running test 306"
#t306: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s306_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t306 2>&1
mv s306_0.wout /home/test/big-drive//subjects/sed/outputs/s306.wout

echo ">>>>>>>>running test 307"
#t307: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s307_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t307 2>&1
mv s307_0.wout /home/test/big-drive//subjects/sed/outputs/s307.wout

echo ">>>>>>>>running test 308"
#t308: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s308_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t308 2>&1
mv s308_0.wout /home/test/big-drive//subjects/sed/outputs/s308.wout

echo ">>>>>>>>running test 309"
#t309: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s309_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t309 2>&1
mv s309_0.wout /home/test/big-drive//subjects/sed/outputs/s309.wout

echo ">>>>>>>>running test 310"
#t310: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s310_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t310 2>&1
mv s310_0.wout /home/test/big-drive//subjects/sed/outputs/s310.wout

echo ">>>>>>>>running test 311"
#t311: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s311_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t311 2>&1
mv s311_0.wout /home/test/big-drive//subjects/sed/outputs/s311.wout

echo ">>>>>>>>running test 312"
#t312: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s312_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t312 2>&1
mv s312_0.wout /home/test/big-drive//subjects/sed/outputs/s312.wout

echo ">>>>>>>>running test 313"
#t313: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s313_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t313 2>&1
mv s313_0.wout /home/test/big-drive//subjects/sed/outputs/s313.wout

echo ">>>>>>>>running test 314"
#t314: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s314_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t314 2>&1
mv s314_0.wout /home/test/big-drive//subjects/sed/outputs/s314.wout

echo ">>>>>>>>running test 315"
#t315: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s315_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t315 2>&1
mv s315_0.wout /home/test/big-drive//subjects/sed/outputs/s315.wout

echo ">>>>>>>>running test 316"
#t316: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s316_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t316 2>&1
mv s316_0.wout /home/test/big-drive//subjects/sed/outputs/s316.wout

echo ">>>>>>>>running test 317"
#t317: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s317_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t317 2>&1
mv s317_0.wout /home/test/big-drive//subjects/sed/outputs/s317.wout

echo ">>>>>>>>running test 318"
#t318: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s318_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t318 2>&1
mv s318_0.wout /home/test/big-drive//subjects/sed/outputs/s318.wout

echo ">>>>>>>>running test 319"
#t319: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s319_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t319 2>&1
mv s319_0.wout /home/test/big-drive//subjects/sed/outputs/s319.wout

echo ">>>>>>>>running test 320"
#t320: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s320_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t320 2>&1
mv s320_0.wout /home/test/big-drive//subjects/sed/outputs/s320.wout

echo ">>>>>>>>running test 321"
#t321: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s321_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t321 2>&1
mv s321_0.wout /home/test/big-drive//subjects/sed/outputs/s321.wout

echo ">>>>>>>>running test 322"
#t322: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s322_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t322 2>&1
mv s322_0.wout /home/test/big-drive//subjects/sed/outputs/s322.wout

echo ">>>>>>>>running test 323"
#t323: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s323_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t323 2>&1
mv s323_0.wout /home/test/big-drive//subjects/sed/outputs/s323.wout

echo ">>>>>>>>running test 324"
#t324: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s324_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t324 2>&1
mv s324_0.wout /home/test/big-drive//subjects/sed/outputs/s324.wout

echo ">>>>>>>>running test 325"
#t325: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s325_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t325 2>&1
mv s325_0.wout /home/test/big-drive//subjects/sed/outputs/s325.wout

echo ">>>>>>>>running test 326"
#t326: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s326_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t326 2>&1
mv s326_0.wout /home/test/big-drive//subjects/sed/outputs/s326.wout

echo ">>>>>>>>running test 327"
#t327: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s327_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t327 2>&1
mv s327_0.wout /home/test/big-drive//subjects/sed/outputs/s327.wout

echo ">>>>>>>>running test 328"
#t328: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s328_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t328 2>&1
mv s328_0.wout /home/test/big-drive//subjects/sed/outputs/s328.wout

echo ">>>>>>>>running test 329"
#t329: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s329_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t329 2>&1
mv s329_0.wout /home/test/big-drive//subjects/sed/outputs/s329.wout

echo ">>>>>>>>running test 330"
#t330: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s330_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t330 2>&1
mv s330_0.wout /home/test/big-drive//subjects/sed/outputs/s330.wout

echo ">>>>>>>>running test 331"
#t331: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s331_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t331 2>&1
mv s331_0.wout /home/test/big-drive//subjects/sed/outputs/s331.wout

echo ">>>>>>>>running test 332"
#t332: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s332_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t332 2>&1
mv s332_0.wout /home/test/big-drive//subjects/sed/outputs/s332.wout

echo ">>>>>>>>running test 333"
#t333: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s333_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t333 2>&1
mv s333_0.wout /home/test/big-drive//subjects/sed/outputs/s333.wout

echo ">>>>>>>>running test 334"
#t334: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s334_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t334 2>&1
mv s334_0.wout /home/test/big-drive//subjects/sed/outputs/s334.wout

echo ">>>>>>>>running test 335"
#t335: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s335_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t335 2>&1
mv s335_0.wout /home/test/big-drive//subjects/sed/outputs/s335.wout

echo ">>>>>>>>running test 336"
#t336: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s336_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t336 2>&1
mv s336_0.wout /home/test/big-drive//subjects/sed/outputs/s336.wout

echo ">>>>>>>>running test 337"
#t337: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s337_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t337 2>&1
mv s337_0.wout /home/test/big-drive//subjects/sed/outputs/s337.wout

echo ">>>>>>>>running test 338"
#t338: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s338_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t338 2>&1
mv s338_0.wout /home/test/big-drive//subjects/sed/outputs/s338.wout

echo ">>>>>>>>running test 339"
#t339: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s339_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t339 2>&1
mv s339_0.wout /home/test/big-drive//subjects/sed/outputs/s339.wout

echo ">>>>>>>>running test 340"
#t340: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s340_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t340 2>&1
mv s340_0.wout /home/test/big-drive//subjects/sed/outputs/s340.wout

echo ">>>>>>>>running test 341"
#t341: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s341_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t341 2>&1
mv s341_0.wout /home/test/big-drive//subjects/sed/outputs/s341.wout

echo ">>>>>>>>running test 342"
#t342: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s342_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t342 2>&1
mv s342_0.wout /home/test/big-drive//subjects/sed/outputs/s342.wout

echo ">>>>>>>>running test 343"
#t343: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s343_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t343 2>&1

echo ">>>>>>>>running test 344"
#t344: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s344_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t344 2>&1

echo ">>>>>>>>running test 345"
#t345: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s345_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t345 2>&1

echo ">>>>>>>>running test 346"
#t346: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s346_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t346 2>&1

echo ">>>>>>>>running test 347"
#t347: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s347_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t347 2>&1

echo ">>>>>>>>running test 348"
#t348: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s348_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t348 2>&1

echo ">>>>>>>>running test 349"
#t349: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s349_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t349 2>&1

echo ">>>>>>>>running test 350"
#t350: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s350_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t350 2>&1

echo ">>>>>>>>running test 351"
#t351: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s351_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t351 2>&1

echo ">>>>>>>>running test 352"
#t352: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s352_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t352 2>&1

echo ">>>>>>>>running test 353"
#t353: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s353_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t353 2>&1

echo ">>>>>>>>running test 354"
#t354: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s354_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t354 2>&1

echo ">>>>>>>>running test 355"
#t355: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s355_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t355 2>&1
mv s355_0.wout /home/test/big-drive//subjects/sed/outputs/s355.wout

echo ">>>>>>>>running test 356"
#t356: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s356_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t356 2>&1
mv s356_0.wout /home/test/big-drive//subjects/sed/outputs/s356.wout

echo ">>>>>>>>running test 357"
#t357: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s357_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t357 2>&1

echo ">>>>>>>>running test 358"
#t358: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s358_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t358 2>&1

echo ">>>>>>>>running test 359"
#t359: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s359_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t359 2>&1

echo ">>>>>>>>running test 360"
#t360: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s360_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t360 2>&1

echo ">>>>>>>>running test 361"
#t361: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s361_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t361 2>&1
mv s361_0.wout /home/test/big-drive//subjects/sed/outputs/s361.wout

echo ">>>>>>>>running test 362"
#t362: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s362_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t362 2>&1
mv s362_0.wout /home/test/big-drive//subjects/sed/outputs/s362.wout

echo ">>>>>>>>running test 363"
#t363: 
/home/test/big-drive//subjects/sed/source//sed.exe -f '../inputs/scr/s363_0.sed' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t363 2>&1
mv s363_0.wout /home/test/big-drive//subjects/sed/outputs/s363.wout

echo ">>>>>>>>running test 364"
#t364: 
/home/test/big-drive//subjects/sed/source//sed.exe -ibak -e's/s/\\/g' ../inputs/inplace.in  > /home/test/big-drive//subjects/sed/outputs/t364 2>&1

echo ">>>>>>>>running test 365"
#t365: 
/home/test/big-drive//subjects/sed/source//sed.exe -i -e's/\\/s/g' ../inputs/inplace.in  > /home/test/big-drive//subjects/sed/outputs/t365 2>&1

echo ">>>>>>>>running test 366"
#t366: 
/home/test/big-drive//subjects/sed/source//sed.exe -l 16 -e's/dog/cat/g; l' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t366 2>&1

echo ">>>>>>>>running test 367"
#t367: 
/home/test/big-drive//subjects/sed/source//sed.exe -r -e's/([Cc]at)|([Dd]og)/MEOWBARK/g' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t367 2>&1

echo ">>>>>>>>running test 368"
#t368: 
/home/test/big-drive//subjects/sed/source//sed.exe -s -e's/dog/cat/gpw s368_0.wout' ../inputs/default.in ../inputs/default2.in  > /home/test/big-drive//subjects/sed/outputs/t368 2>&1
mv s368_0.wout /home/test/big-drive//subjects/sed/outputs/s368.wout

echo ">>>>>>>>running test 369"
#t369: 
/home/test/big-drive//subjects/sed/source//sed.exe -u -e's/dog/DOG/gp' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t369 2>&1

echo ">>>>>>>>running test 370"
#t370: 
/home/test/big-drive//subjects/sed/source//sed.exe -rsul 20 -e's/([Cc]at)|([Dd]og)/MEOWBARK/g; l' ../inputs/default.in  > /home/test/big-drive//subjects/sed/outputs/t370 2>&1

